apiVersion: v1
kind: Pod
metadata:
  name: oracle-xe
  labels:
    app: oracle
spec: 
  containers: 
    - name: oracle-xe
      image: gvenzl/oracle-xe:latest
      #image: container-registry.oracle.com/database/express:latest
      env: 
        - name: ORACLE_PASSWORD
          value: ABC12345
